site_name: RIMS-Code
site_url: https://rims-code.github.io
repo_url: https://github.com/RIMS-Code
site_author: RIMS-Code team
theme:
  name: material
  features:
  - content.code.copy
  - content.code.select
  - navigation.footer
  palette:
  - scheme: slate
    toggle:
      icon: material/brightness-2
      name: Switch to light mode
    primary: indigo
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
    primary: indigo
markdown_extensions:
- admonition
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.arithmatex:
    generic: true
extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
- Home: index.md
- Schemes:
  - Periodic Table: schemes.md
  - Elements:
    - Zr:
      - Overview: schemes/zr/index.md
      - Zr-1: schemes/zr/zr-001.md
    - W:
      - Overview: schemes/w/index.md
      - W-1: schemes/w/w-001.md
- Contribute: contribute.md
- Submit a Scheme: submit_scheme.md
- Crystal calculator: crystal-calculator.md
- Maintainers: maintainers.md
