site_name: RIMS-Code
site_url: https://rims-code.github.io
repo_url: https://github.com/RIMS-Code
site_author: RIMS-Code team
theme:
  name: material
  features:
  - content.code.copy
  - content.code.select
  - navigation.footer
  palette:
  - scheme: slate
    toggle:
      icon: material/brightness-2
      name: Switch to light mode
    primary: indigo
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
    primary: indigo
markdown_extensions:
- admonition
- attr_list
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.arithmatex:
    generic: true
plugins:
- privacy
- search
extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
- Home: index.md
- Schemes:
  - Periodic Table: schemes/schemes.md
  - Elements:
    - Ti:
      - Overview: schemes/ti/index.md
      - Ti-1: schemes/ti/ti-001.md
    - Fe:
      - Overview: schemes/fe/index.md
      - Fe-1: schemes/fe/fe-001.md
    - Ni:
      - Overview: schemes/ni/index.md
      - Ni-1: schemes/ni/ni-001.md
    - Zr:
      - Overview: schemes/zr/index.md
      - Zr-1: schemes/zr/zr-001.md
    - Ba:
      - Overview: schemes/ba/index.md
      - Ba-1: schemes/ba/ba-001.md
    - W:
      - Overview: schemes/w/index.md
      - W-1: schemes/w/w-001.md
  - Submit a Scheme: schemes_static/submit_scheme.md
  - Information: schemes_static/info.md
- Tools:
  - Crystal calculator: tools/crystal-calculator.md
  - RIMS Scheme Drawer: tools/rimsschemedrawer.md
- About:
  - Contribute: about/contribute.md
  - Maintainers: about/maintainers.md
  - Maintainers manual: about/maintainers_manual.md
