name: Rebuild the whole website (manual dispatch)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v2
    - name: Build website with rye
      run: |
        rye sync --all-features
        rye run rebuild
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -a -m "Update website."
    - name: Create PR
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: rebuild website
        title: Rebuild website
        body: |
          This PR is a rebuild of the whole website.
        branch: rebuild_website
        draft: false
